spring:
  redis:
    #redis数据库索引(默认为0)
    database: 0
    #redis服务器IP地址
    host: 39.108.14.141
    #redis端口号
    port: 6382
    #redis密码
    password: 123456
    #连接redis超时时间（毫秒）
#    timeout:
    #jedis连接池
    cluster:
      nodes:
        - 39.108.14.141:7000
        - 39.108.14.141:7001
        - 39.108.14.141:7002
        - 39.108.14.141:7003
        - 39.108.14.141:7004
        - 39.108.14.141:7005
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

  # MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/non_tax?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: password

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

redis:
  # 每次从关系型数据库中获取的号码数量
  getNumEveryTime: 5000

