spring:
  application:
    name: nacos-service-usm
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
      config:
        server-addr: localhost:8848
        file-extension: yaml #指定yaml格式的配置
    profiles:
      active: dev
  rabbitmq:
    host: 192.168.110.128
    username: guest
    password: guest
  profiles:
    active: zdh

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true



